#pragma config(Sensor, S1,     lightsensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//declare function shrek and int variables for motor love=power and life=time
void shrek(int love, int life)
{
	motor[motorA] = love;
	motor[motorB] = love;
	wait1Msec(life);
}

//while sensor value (light level) of light sensor is not 40 (a dark surface e.g. duct tape), robot goes forward.
//foward until dark
task main()
{

if (SensorValue(lightsensor)>40)
{
	shrek(50, 100);
}
	shrek(0, 10000);
}
