#pragma config(Sensor, S1,     lightsensor,    sensorLightActive)
#pragma config(Sensor, S2,     touchsensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//for this program to work, the light sensor must start to the right of the black line.


task main()
{
	int modifier = 0;
	if(SensorValue(touchsensor) == 1)
	{
		if modifier = 3;
			int modifier = 0;
			else
			{modifier++;
	}
}

	switch(modifier)
	{

	case 0
	//do somthing
	case
}
