#pragma config(Sensor, S1,     touchsensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//declare function drive (set all motors' power) equal to variable power.
void drive(int power, int time)
{
	motor[motorA] = power;
	motor[motorB] = power;
	motor[motorC] = power;
	wait1Msec(time);
}

//task main
task main()
{
	//while the sensor value is triggered, the robot does not move.
	while(SensorValue(touchsensor)==1)
	{
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	}
	//otherwise the robot wiill drive at specified values for 1 second each.
	drive(100, 1000);
	drive(50, 1000);
	drive(40, 1000);
	drive(30, 1000);
	drive(-50, 1000);
}
