#pragma config(Sensor, S1,     sonarsensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//declare function shrek and int variables love=power and life=time
void shrek(int love, int life)
{
	motor[motorA] = love;
	motor[motorB] = love;
	wait1Msec(life);
}

//while sensor value of sonarsensor is over 25 cm go forward with 50 power. Once robot is 25 cm away, stop moving and wait for 10 seconds.
task main()
{

while (SensorValue(sonarsensor)>25)
{
	motor[motorA] = 50;
	motor[motorB] = 50;

}
	shrek(0, 10000);
}
